import './public-site.css';
import Link from 'next/link';
import { BrandLogo } from '@/components/brand-logo';

export function Mark() { return <span className="mark" aria-hidden="true"><BrandLogo variant="icon" decorative className="h-full w-full object-contain" /></span>; }
export function Brand({light=false}:{light?:boolean}) { return <Link href="/" className={`brand ${light?'light':''}`} aria-label="Student.social home"><BrandLogo variant="icon" tone={light?'inverse':'default'} decorative priority className="h-11 w-11 object-contain" /><sup>BETA</sup></Link>; }
export function Nav() { return <header className="site-nav container"><Brand light /><nav className="desktop-nav" aria-label="Primary"><Link href="/#features">Features</Link><Link href="/#how-it-works">How it works</Link><Link href="/about">About</Link><details><summary>Resources <span>⌄</span></summary><div><Link href="/help">Help center</Link><Link href="/demo">Product demo</Link><Link href="/blog">Learning journal</Link><Link href="/status">Platform status</Link></div></details></nav><div className="nav-actions"><Link href="/login" className="sign-link">Sign in</Link><Link href="/register" className="button small cream">Get started →</Link></div><details className="mobile-menu"><summary aria-label="Open navigation"><span></span><span></span></summary><div><Link href="/#features">Features</Link><Link href="/#how-it-works">How it works</Link><Link href="/about">About</Link><Link href="/demo">Product demo</Link><Link href="/blog">Learning journal</Link><Link href="/help">Help center</Link><Link href="/status">Platform status</Link><Link href="/contact">Contact</Link><Link href="/login">Sign in</Link><Link href="/register">Get started</Link></div></details></header>; }
export function PublicNav() { return <div className="public-nav-wrap"><Nav /></div>; }
export function Footer() { const groups=[['Explore',['Features|/#features','How it works|/#how-it-works','Product demo|/demo','Learning journal|/blog']],['Company',['About|/about','Support the project|/support','Contact|/contact','Preview status|/status']],['Help',['Help center|/help','Community guidelines|/community-guidelines','Accessibility|/accessibility']],['Legal',['Privacy|/privacy','Terms|/terms','Cookies|/cookies','DMCA|/dmca']]];return <footer className="site-footer"><div className="container footer-grid"><div className="footer-brand"><Brand light /><p>Learning feels lighter when the right people are within reach.</p><span>Student-led · Built in public</span></div>{groups.map(([title,items])=><div className="footer-group" key={title as string}><b>{title}</b>{(items as string[]).map(item=>{const [label,href]=item.split('|');return <Link key={label} href={href}>{label}</Link>})}</div>)}</div><div className="container footer-bottom"><span>© 2026 Student.social preview</span><span>No production account or live monitoring is connected.</span></div></footer>; }
export function SectionLabel({number,label}:{number:string,label:string}) { return <div className="section-label"><span>{number}</span><b>{label}</b></div>; }
export function AvatarStack() { return <div className="avatar-stack" aria-label="Four circle members"><i className="avatar avatar-rust">AM</i><i className="avatar avatar-olive">SK</i><i className="avatar avatar-plum">JL</i><i className="avatar avatar-amber">+4</i></div>; }
export function PhoneMock() { return <div className="phone"><div className="phone-top"><span>9:41</span><i /><span>● ◒</span></div><div className="phone-app"><div className="phone-brand"><BrandLogo variant="icon" decorative className="h-6 w-6 object-contain" /><span>⌕</span></div><div className="stories"><div><i className="story rust">P</i><span>Python</span></div><div><i className="story olive">C</i><span>Calculus</span></div><div><i className="story plum">D</i><span>Design</span></div><div><i className="story amber">+</i><span>Explore</span></div></div><div className="feed-card"><div className="feed-author"><i className="avatar avatar-rust">AM</i><div><b>Aarav · Python beginners</b><span>12 min ago</span></div><span>•••</span></div><p>Finally understood list comprehensions. Here’s the little visual trick that made it click:</p><div className="code-note"><span>old loop</span><b>[x² for x in numbers]</b><em>same idea, one clear line</em></div><div className="feed-meta"><span>♡ 18</span><span>◯ 6</span><span>↗ Share</span></div></div><div className="feed-card mini-feed"><div className="feed-author"><i className="avatar avatar-olive">SK</i><div><b>Sana · Calculus circle</b><span>32 min ago</span></div></div><p>Focus room opens in 20 minutes. We’re doing limits, gently.</p><button>Join study room →</button></div><div className="phone-nav"><b>⌂<small>Home</small></b><span>◎<small>Circles</small></span><span>＋<small>Post</small></span><span>✦<small>Tutor</small></span></div></div></div>; }
export function FeatureCard({number,title,text,accent}:{number:string,title:string,text:string,accent:string}) { return <article className={`feature-card ${accent}`}><span>{number}</span><div className="feature-symbol" aria-hidden="true">{number==='01'?'◎':number==='02'?'✦':number==='03'?'↗':number==='04'?'▤':number==='05'?'◌':'◇'}</div><h3>{title}</h3><p>{text}</p><Link href="/demo">See how it works →</Link></article>; }
export function ProductMoment({label,title,meta,accent}:{label:string,title:string,meta:string,accent:string}) { return <article className={`moment-card ${accent}`}><span>{label}</span><h3>{title}</h3><p>{meta}</p><div className="moment-actions"><i>♡</i><i>◯</i><i>↗</i></div></article>; }
export function CtaBand() { return <section className="cta-band"><div className="container"><span className="eyebrow light">YOUR NEXT STUDY SESSION</span><h2>Come as you are.<br /><em>Leave less stuck.</em></h2><p>Student.social is an early, student-led preview of a more human way to learn online.</p><div><Link className="button cream" href="/register">Create a preview account →</Link><Link className="button ghost" href="/demo">Take the product tour</Link></div></div></section>; }
export function Newsletter() { return <section className="newsletter"><div className="container newsletter-grid"><div><span className="eyebrow">LEARNING JOURNAL</span><h2>Notes from building in public.</h2><p>Product thinking, study experiments, and honest progress—occasionally, not noisily.</p></div><form><label className="sr-only" htmlFor="newsletter-email">Email address</label><input id="newsletter-email" type="email" placeholder="you@example.com" /><button>Keep me posted →</button><small>Preview form · no mailing service connected yet.</small></form></div></section>; }
