export const databaseId =
  process.env.APPWRITE_DATABASE_ID ||
  process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID ||
  "peerspark-main-db"

export const collections = [
  {
    id: "pods",
    name: "Pods",
    strings: [["name", 160, true], ["slug", 180, true], ["shortOutcome", 280, true], ["description", 4000, false], ["category", 120, false], ["difficulty", 40, false], ["language", 80, false], ["coverImageId", 160, false], ["coverImageUrl", 1000, false], ["creatorId", 160, true], ["mentorId", 160, false], ["type", 60, false], ["visibility", 40, false], ["status", 40, false], ["currentSprintId", 160, false], ["weeklyRhythm", 500, false], ["defaultSessionDay", 40, false], ["defaultSessionTime", 40, false], ["timezone", 100, false]],
    integers: [["maxMembers", false], ["currentWeek", false], ["totalWeeks", false], ["memberCount", false], ["activeMemberCount", false]],
    floats: [["completionRate", false], ["weeklyActivityScore", false], ["healthScore", false]],
    booleans: [["approvalRequired", false]],
    datetimes: [["nextSessionAt", false], ["createdAt", true], ["updatedAt", true]],
    stringArrays: [["tags", 80, false]],
    indexes: [["slug_unique", "unique", ["slug"]], ["creatorId", "key", ["creatorId"]], ["category", "key", ["category"]], ["difficulty", "key", ["difficulty"]], ["visibility", "key", ["visibility"]], ["status", "key", ["status"]], ["nextSessionAt", "key", ["nextSessionAt"]], ["weeklyActivityScore", "key", ["weeklyActivityScore"]], ["createdAt", "key", ["createdAt"]]],
  },
  {
    id: "pod_memberships",
    name: "Pod Memberships",
    strings: [["podId", 160, true], ["userId", 160, true], ["role", 40, true], ["status", 40, true], ["availability", 500, false], ["notificationPreference", 40, false]],
    integers: [["currentStreak", false], ["totalPoints", false], ["tasksCompleted", false], ["sessionsAttended", false], ["resourcesShared", false], ["peerReviewsCompleted", false], ["checkInsCount", false]],
    floats: [["progressPercent", false], ["contributionScore", false]],
    datetimes: [["joinedAt", false], ["lastActiveAt", false], ["createdAt", true], ["updatedAt", true]],
    stringArrays: [["skills", 80, false]],
    indexes: [["podId", "key", ["podId"]], ["userId", "key", ["userId"]], ["role", "key", ["role"]], ["status", "key", ["status"]], ["totalPoints", "key", ["totalPoints"]], ["currentStreak", "key", ["currentStreak"]], ["lastActiveAt", "key", ["lastActiveAt"]], ["pod_user_unique", "unique", ["podId", "userId"]]],
  },
  {
    id: "pod_roadmap_items",
    name: "Pod Roadmap Items",
    strings: [["podId", 160, true], ["parentId", 160, false], ["phaseId", 160, false], ["title", 240, true], ["description", 4000, false], ["type", 40, true], ["status", 40, false], ["difficulty", 40, false], ["sessionId", 160, false], ["unlockRule", 500, false], ["createdBy", 160, false]],
    integers: [["week", false], ["day", false], ["order", false], ["estimatedMinutes", false], ["points", false]],
    datetimes: [["dueAt", false], ["createdAt", true], ["updatedAt", true]],
    stringArrays: [["resourceIds", 160, false], ["taskIds", 160, false]],
    indexes: [["podId", "key", ["podId"]], ["type", "key", ["type"]], ["week", "key", ["week"]], ["status", "key", ["status"]], ["order", "key", ["order"]], ["dueAt", "key", ["dueAt"]]],
  },
  {
    id: "pod_tasks",
    name: "Pod Tasks",
    strings: [["podId", 160, true], ["roadmapItemId", 160, false], ["title", 240, true], ["description", 4000, false], ["type", 60, false], ["priority", 40, false], ["status", 40, false], ["assignedRole", 60, false], ["createdBy", 160, false], ["difficulty", 40, false], ["submissionType", 40, false]],
    integers: [["points", false], ["order", false]],
    booleans: [["required", false], ["allowLateSubmission", false]],
    datetimes: [["dueAt", false], ["createdAt", true], ["updatedAt", true]],
    stringArrays: [["assignedTo", 160, false], ["relatedResourceIds", 160, false]],
    indexes: [["podId", "key", ["podId"]], ["roadmapItemId", "key", ["roadmapItemId"]], ["status", "key", ["status"]], ["dueAt", "key", ["dueAt"]], ["createdBy", "key", ["createdBy"]], ["priority", "key", ["priority"]]],
  },
  {
    id: "pod_task_submissions",
    name: "Pod Task Submissions",
    strings: [["podId", 160, true], ["taskId", 160, true], ["userId", 160, true], ["status", 40, true], ["text", 6000, false], ["link", 1000, false], ["feedback", 4000, false], ["reviewedBy", 160, false]],
    integers: [["pointsAwarded", false]],
    booleans: [["late", false]],
    datetimes: [["reviewedAt", false], ["submittedAt", false], ["createdAt", true], ["updatedAt", true]],
    stringArrays: [["fileIds", 160, false]],
    indexes: [["podId", "key", ["podId"]], ["taskId", "key", ["taskId"]], ["userId", "key", ["userId"]], ["status", "key", ["status"]], ["submittedAt", "key", ["submittedAt"]], ["reviewedBy", "key", ["reviewedBy"]]],
  },
  {
    id: "pod_sessions",
    name: "Pod Sessions",
    strings: [["podId", 160, true], ["title", 240, true], ["description", 4000, false], ["type", 60, false], ["status", 40, false], ["timezone", 100, false], ["hostId", 160, false], ["agenda", 6000, false], ["meetingProvider", 80, false], ["meetingUrl", 1000, false], ["recordingUrl", 1000, false], ["whiteboardStateId", 160, false], ["notesResourceId", 160, false]],
    integers: [["maxParticipants", false]],
    booleans: [["reminderSent", false]],
    datetimes: [["startsAt", true], ["endsAt", false], ["createdAt", true], ["updatedAt", true]],
    indexes: [["podId", "key", ["podId"]], ["status", "key", ["status"]], ["startsAt", "key", ["startsAt"]], ["hostId", "key", ["hostId"]]],
  },
  {
    id: "pod_session_attendance",
    name: "Pod Session Attendance",
    strings: [["podId", 160, true], ["sessionId", 160, true], ["userId", 160, true], ["status", 40, false], ["notes", 2000, false]],
    integers: [["durationMinutes", false]],
    floats: [["participationScore", false]],
    datetimes: [["joinedAt", false], ["leftAt", false], ["createdAt", true]],
    indexes: [["podId", "key", ["podId"]], ["sessionId", "key", ["sessionId"]], ["userId", "key", ["userId"]], ["status", "key", ["status"]]],
  },
  {
    id: "pod_resources",
    name: "Pod Resources",
    strings: [["podId", 160, true], ["uploaderId", 160, true], ["title", 240, true], ["description", 4000, false], ["type", 60, false], ["storageFileId", 160, false], ["url", 1000, false], ["content", 10000, false], ["visibility", 40, false], ["attachedToType", 60, false], ["attachedToId", 160, false]],
    integers: [["views", false], ["downloads", false], ["bookmarks", false], ["usefulCount", false]],
    datetimes: [["createdAt", true], ["updatedAt", true]],
    stringArrays: [["tags", 80, false]],
    indexes: [["podId", "key", ["podId"]], ["uploaderId", "key", ["uploaderId"]], ["type", "key", ["type"]], ["visibility", "key", ["visibility"]], ["attachedToType", "key", ["attachedToType"]], ["attachedToId", "key", ["attachedToId"]], ["createdAt", "key", ["createdAt"]]],
  },
  {
    id: "pod_checkins",
    name: "Pod Checkins",
    strings: [["podId", 160, true], ["userId", 160, true], ["date", 20, true], ["mood", 40, false], ["status", 40, false], ["todayPlan", 4000, false], ["yesterdayProgress", 4000, false], ["blocker", 4000, false]],
    booleans: [["helpNeeded", false]],
    integers: [["streakCountAfter", false], ["pointsAwarded", false]],
    datetimes: [["createdAt", true], ["updatedAt", true]],
    stringArrays: [["relatedTaskIds", 160, false]],
    indexes: [["podId", "key", ["podId"]], ["userId", "key", ["userId"]], ["date", "key", ["date"]], ["status", "key", ["status"]], ["helpNeeded", "key", ["helpNeeded"]]],
  },
  {
    id: "pod_chat_channels",
    name: "Pod Chat Channels",
    strings: [["podId", 160, true], ["name", 100, true], ["slug", 120, true], ["description", 1000, false], ["type", 60, false], ["postingRole", 60, false], ["createdBy", 160, false]],
    integers: [["order", false]],
    booleans: [["locked", false]],
    datetimes: [["createdAt", true], ["updatedAt", true]],
    indexes: [["podId", "key", ["podId"]], ["slug", "key", ["slug"]], ["type", "key", ["type"]], ["order", "key", ["order"]]],
  },
  {
    id: "pod_messages",
    name: "Pod Messages",
    strings: [["podId", 160, true], ["channelId", 160, true], ["senderId", 160, true], ["content", 10000, false], ["type", 60, false], ["label", 60, false], ["replyToMessageId", 160, false], ["threadRootId", 160, false]],
    booleans: [["pinned", false], ["important", false], ["edited", false], ["deleted", false]],
    datetimes: [["editedAt", false], ["deletedAt", false], ["createdAt", true], ["updatedAt", true]],
    stringArrays: [["attachmentIds", 160, false]],
    indexes: [["podId", "key", ["podId"]], ["channelId", "key", ["channelId"]], ["senderId", "key", ["senderId"]], ["label", "key", ["label"]], ["replyToMessageId", "key", ["replyToMessageId"]], ["threadRootId", "key", ["threadRootId"]], ["createdAt", "key", ["createdAt"]], ["pinned", "key", ["pinned"]], ["important", "key", ["important"]]],
  },
  {
    id: "pod_message_reactions",
    name: "Pod Message Reactions",
    strings: [["podId", 160, true], ["messageId", 160, true], ["userId", 160, true], ["emoji", 32, true]],
    datetimes: [["createdAt", true]],
    indexes: [["messageId", "key", ["messageId"]], ["userId", "key", ["userId"]], ["emoji", "key", ["emoji"]], ["reaction_unique", "unique", ["messageId", "userId", "emoji"]]],
  },
  {
    id: "pod_insights",
    name: "Pod Insights",
    strings: [["podId", 160, true], ["scope", 40, true], ["userId", 160, false], ["period", 40, true]],
    floats: [["progressPercent", false], ["consistencyScore", false], ["attendanceRate", false], ["taskCompletionRate", false], ["dropOffRisk", false]],
    integers: [["activeMembers", false], ["inactiveMembers", false]],
    datetimes: [["periodStart", true], ["periodEnd", true], ["generatedAt", true]],
    stringArrays: [["mostAskedTopics", 120, false], ["suggestedActions", 240, false]],
    indexes: [["podId", "key", ["podId"]], ["userId", "key", ["userId"]], ["scope", "key", ["scope"]], ["period", "key", ["period"]], ["periodStart", "key", ["periodStart"]]],
  },
  {
    id: "pod_invites",
    name: "Pod Invites",
    strings: [["podId", 160, true], ["invitedBy", 160, false], ["invitedEmail", 240, false], ["invitedUserId", 160, false], ["status", 40, true], ["inviteCode", 160, false], ["role", 40, false]],
    datetimes: [["expiresAt", false], ["createdAt", true], ["updatedAt", true]],
    indexes: [["podId", "key", ["podId"]], ["invitedEmail", "key", ["invitedEmail"]], ["invitedUserId", "key", ["invitedUserId"]], ["inviteCode", "key", ["inviteCode"]], ["status", "key", ["status"]], ["expiresAt", "key", ["expiresAt"]]],
  },
  {
    id: "pod_notifications_queue",
    name: "Pod Notifications Queue",
    strings: [["podId", 160, false], ["userId", 160, false], ["type", 80, true], ["title", 240, true], ["body", 2000, false], ["targetUrl", 1000, false], ["status", 40, true], ["metadata", 10000, false]],
    datetimes: [["scheduledFor", true], ["sentAt", false], ["createdAt", true]],
    indexes: [["podId", "key", ["podId"]], ["userId", "key", ["userId"]], ["type", "key", ["type"]], ["scheduledFor", "key", ["scheduledFor"]], ["status", "key", ["status"]]],
  },
]

export const buckets = [
  { id: "pod-covers", name: "Pod Covers", size: 5 * 1024 * 1024, extensions: ["jpg", "jpeg", "png", "webp"] },
  { id: "pod-resources", name: "Pod Resources", size: 50 * 1024 * 1024, extensions: ["pdf", "png", "jpg", "jpeg", "webp", "mp4", "mov", "mp3", "wav", "txt", "md", "zip", "js", "ts", "jsx", "tsx", "py", "java", "cpp", "html", "css"] },
  { id: "pod-chat-attachments", name: "Pod Chat Attachments", size: 25 * 1024 * 1024, extensions: ["pdf", "png", "jpg", "jpeg", "webp", "mp4", "mov", "mp3", "wav", "txt", "md", "zip", "js", "ts", "jsx", "tsx", "py", "html", "css"] },
  { id: "pod-session-recordings", name: "Pod Session Recordings", size: 100 * 1024 * 1024, extensions: ["mp4", "mov", "mp3", "wav", "txt", "md"] },
]
